apiVersion: v1
kind: ConfigMap
metadata:
  name: my-project2
  namespace: mongodb
data:
  baseUrl: http://ops-manager-svc.mongodb.svc.cluster.local:8080

  # Optional Parameters
  projectName: MongoDBUser

  orgId: 68de226b000c5b1d29192859
---
apiVersion: v1
kind: Secret
metadata:
  name: organization-secret2
  namespace: mongodb
stringData:
  user: bjlzmsdp
  publicApiKey: 2dda0ab2-5aa2-4840-8d02-3de46d531b60