apiVersion: v1
kind: ConfigMap
metadata:
  name: my-project
  namespace: mongodb
data:
  baseUrl: http://ops-manager-svc.mongodb.svc.cluster.local:8080

  # Optional Parameters
  projectName: MongoDBExternal

  orgId: 68dfb39bb90bc7368bccfab9
---
apiVersion: v1
kind: Secret
metadata:
  name: organization-secret
  namespace: mongodb
stringData:
  user: secerwjx
  publicApiKey: 64a9ea0d-31c3-44a5-8a38-5a5707384030