apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: mongodb
spec:
  containers:
  - name: app-container
    image: pix3lize/mdbubuntu
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"